# .github/workflows/deploy.yml
name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Install Aspire CLI
        run: dotnet tool install --global aspire.cli --prerelease --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json

      - name: Enable deploy command
        run: aspire config set features.deployCommandEnabled true -g

      - name: Deploy to Digital Ocean
        env:
          # ALL the configuration from the README
          DOCKERSSH__SSHHOST: ${{ secrets.DO_HOST }}
          DOCKERSSH__SSHUSERNAME: ${{ secrets.DO_USERNAME }}
          DOCKERSSH__SSHPORT: "22"
          DOCKERSSH__SSHKEYPATH: "/home/runner/.ssh/id_rsa"
          DOCKERSSH__REMOTEDEPLOYPATH: "/home/root/aspire-app"
          DOCKERSSH__REGISTRYURL: "docker.io"
          DOCKERSSH__REPOSITORYPREFIX: "commandor"
          
          # Image and port variables that get prompted for
          APISERVICE_IMAGE: "docker.io/commandor/apiservice:latest"
          APISERVICE_PORT: "8080"
          WEBFRONTEND_IMAGE: "docker.io/commandor/webfrontend:latest"
          WEBFRONTEND_PORT: "8080"
          CACHE_PASSWORD: "redis123!"
        
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add host to known_hosts
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
          
          # Change to the correct directory
          cd samples/DockerPipelinesSample/DockerPipelinesSample.AppHost
          
          # Deploy with all environment variables set
          aspire deploy