# .github/workflows/deploy.yml  
name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Generate manifest
        run: |
          cd samples/DockerPipelinesSample/DockerPipelinesSample.AppHost
          dotnet run --publisher manifest --output-path ./manifest.json

      - name: Build and push images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          cd samples/DockerPipelinesSample
          
          # Build for x86_64 (this will work on GitHub's x86_64 runners)
          docker build -t commandor/apiservice:${{ github.sha }} ./DockerPipelinesSample.ApiService
          docker build -t commandor/webfrontend:${{ github.sha }} ./DockerPipelinesSample.Web
          
          # Push to Docker Hub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push commandor/apiservice:${{ github.sha }}
          docker push commandor/webfrontend:${{ github.sha }}

      - name: Deploy to Digital Ocean
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
          
          # Create docker-compose.yml on the server
          ssh -i ~/.ssh/id_rsa root@${{ secrets.DO_HOST }} "mkdir -p /opt/aspire-app"
          
          # Upload and run docker-compose
          cat > docker-compose.yml << EOF
          services:
            webfrontend:
              image: commandor/webfrontend:${{ github.sha }}
              ports:
                - "80:8080"
            apiservice:
              image: commandor/apiservice:${{ github.sha }}
              ports:
                - "8080:8080"
            redis:
              image: redis:7.4
              ports:
                - "6379:6379"
          EOF
          
          scp -i ~/.ssh/id_rsa docker-compose.yml root@${{ secrets.DO_HOST }}:/opt/aspire-app/
          ssh -i ~/.ssh/id_rsa root@${{ secrets.DO_HOST }} "cd /opt/aspire-app && docker-compose up -d"