# .github/workflows/deploy.yml
name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Install Aspire CLI
        run: dotnet tool install --global aspire.cli --prerelease --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json

      - name: Enable deploy command
        run: aspire config set features.deployCommandEnabled true -g

      - name: Create deployment configuration
        run: |
          cd samples/DockerPipelinesSample/DockerPipelinesSample.AppHost
          
          # Create appsettings.json with deployment configuration
          cat > appsettings.json << EOF
          {
            "DockerSSH": {
              "SshHost": "${{ secrets.DO_HOST }}",
              "SshUsername": "${{ secrets.DO_USERNAME }}",
              "SshPort": "22",
              "SshKeyPath": "/home/runner/.ssh/id_rsa",
              "RemoteDeployPath": "/home/root/aspire-app",
              "RegistryUrl": "docker.io",
              "RepositoryPrefix": "commandor"
            }
          }
          EOF

      - name: Deploy to Digital Ocean
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add host to known_hosts
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
          
          # Change to the correct directory
          cd samples/DockerPipelinesSample/DockerPipelinesSample.AppHost
          
          # Try deploy with --non-interactive flag
          aspire deploy --non-interactive